CREATE TABLE alert (
	"UId" VARCHAR NOT NULL, 
	"ClinicId" VARCHAR NOT NULL, 
	"PatientStayUId" VARCHAR NOT NULL, 
	"PatientPhaseUId" VARCHAR NOT NULL, 
	"AlertTypeId" VARCHAR NOT NULL, 
	"AlertLevel" VARCHAR NOT NULL, 
	"AlertStatusId" VARCHAR NOT NULL, 
	"IsActive" VARCHAR NOT NULL, 
	"NumberOfOpening" VARCHAR NOT NULL, 
	"CreatedOn" VARCHAR NOT NULL, 
	"FirstOpenedAt" VARCHAR, 
	"LastOpenedAt" VARCHAR, 
	"SuspendedAt" VARCHAR, 
	"ClosedAt" VARCHAR, 
	"LastOpenedByUId" VARCHAR, 
	"SuspendedByUId" VARCHAR, 
	"ClosedByUId" VARCHAR, 
	"SuspendComments" VARCHAR, 
	"CorrelationEntity" VARCHAR, 
	"CorrelationUId" VARCHAR, 
	"LastChangeDate" VARCHAR NOT NULL, 
	"AlertMessage" VARCHAR NOT NULL, 
	"Comments" VARCHAR
);
CREATE TABLE alert_subitem (
	"UId" VARCHAR NOT NULL, 
	"EntityType" VARCHAR NOT NULL, 
	"CorrelationUId" VARCHAR NOT NULL, 
	"ItemNo" VARCHAR NOT NULL, 
	"AlertTypeId" VARCHAR NOT NULL, 
	"AlertMessage" VARCHAR NOT NULL, 
	"ThresholdOnly" VARCHAR NOT NULL
);
CREATE TABLE clinic (
	"Id" VARCHAR NOT NULL, 
	"Clinic name" VARCHAR NOT NULL, 
	"Has medical department" VARCHAR NOT NULL
);
CREATE TABLE clinic_doctor_hospit_followup (
	"#Clinic" VARCHAR NOT NULL, 
	"Clinic" VARCHAR NOT NULL, 
	"#Doctor" VARCHAR NOT NULL, 
	"Doctor" VARCHAR NOT NULL, 
	"#Hospitalization reason" VARCHAR NOT NULL, 
	"Hospitalization reason" VARCHAR NOT NULL, 
	"#Follow up reason" VARCHAR NOT NULL, 
	"Follow up reason" VARCHAR NOT NULL
);
CREATE TABLE clinic_followup_reason (
	"#Clinic" VARCHAR NOT NULL, 
	"Clinic" VARCHAR NOT NULL, 
	"#Follow up reason" VARCHAR NOT NULL, 
	"Follow up reason code" VARCHAR NOT NULL, 
	"Follow up reason" VARCHAR NOT NULL
);
CREATE TABLE data_alert_delay (
	"#Alert" VARCHAR NOT NULL, 
	"Year" VARCHAR NOT NULL, 
	"Month" VARCHAR NOT NULL, 
	"Week" VARCHAR NOT NULL, 
	"Fortnight" VARCHAR NOT NULL, 
	"#Clinic" VARCHAR NOT NULL, 
	"#Medical Dept" VARCHAR, 
	"#Alert Type" VARCHAR NOT NULL, 
	"#Doctor" VARCHAR NOT NULL, 
	"#Hospitalization Reason" VARCHAR NOT NULL, 
	"#Follow Up Reason" VARCHAR NOT NULL, 
	"Alert Raised At" VARCHAR NOT NULL, 
	"Alert First Openning At" VARCHAR NOT NULL, 
	"Alert Last Openning At" VARCHAR, 
	"Alert Closed At" VARCHAR NOT NULL, 
	"Number Of Openning" VARCHAR NOT NULL, 
	"Take In Charge Time (second)" VARCHAR NOT NULL, 
	"Treatment Time (second)" VARCHAR, 
	"Total Treatment Time (second)" VARCHAR NOT NULL, 
	"Total Active Time (second)" VARCHAR NOT NULL
);
CREATE TABLE data_alert_notresponding (
	"#Alert" VARCHAR NOT NULL, 
	"#Clinic" VARCHAR NOT NULL, 
	"Clinique" VARCHAR NOT NULL, 
	"#Medical Dept" VARCHAR NOT NULL, 
	"Service" VARCHAR, 
	"#Doctor" VARCHAR NOT NULL, 
	"Médecin" VARCHAR NOT NULL, 
	"#Patient" VARCHAR NOT NULL, 
	"#Séjour" VARCHAR NOT NULL, 
	"Séjour no" VARCHAR, 
	"Date d'intervention" VARCHAR NOT NULL, 
	"#HospitalizationReason" VARCHAR NOT NULL, 
	"Motif d'hospitalisation" VARCHAR NOT NULL, 
	"#FollowUpReason" VARCHAR NOT NULL, 
	"Motif de suivi" VARCHAR NOT NULL, 
	"Phase" VARCHAR NOT NULL, 
	"Evènement à I+X" VARCHAR NOT NULL, 
	"Evènement à S+X" VARCHAR NOT NULL, 
	"Alerte déclenchée le" VARCHAR NOT NULL, 
	"Première prise en charge" VARCHAR NOT NULL, 
	"Alerte close le" VARCHAR NOT NULL, 
	"Commentiaire de clôture" VARCHAR NOT NULL
);
CREATE TABLE data_demography (
	"Year" VARCHAR NOT NULL, 
	"Month" VARCHAR NOT NULL, 
	"WeekNumber" VARCHAR NOT NULL, 
	"Fortnight" VARCHAR NOT NULL, 
	"#Clinic" VARCHAR NOT NULL, 
	"#MedicalDepartment" VARCHAR NOT NULL, 
	"#Doctor" VARCHAR NOT NULL, 
	"#Hospitalization Reason" VARCHAR NOT NULL, 
	"#Follow Up Reason" VARCHAR NOT NULL, 
	"#Gender" VARCHAR NOT NULL, 
	"Age Gone" VARCHAR NOT NULL, 
	"Age Distribution" VARCHAR NOT NULL, 
	"Number" VARCHAR NOT NULL
);
CREATE TABLE data_preadmission (
	"Year" VARCHAR, 
	"Month" VARCHAR, 
	"WeekNumber" VARCHAR, 
	"Fortnight" VARCHAR, 
	"#Clinic" VARCHAR, 
	"#MedicalDepartment" VARCHAR, 
	"#Doctor" VARCHAR, 
	"#Hospitalization Reason" VARCHAR, 
	"#Follow Up Reason" VARCHAR, 
	"FormCode" VARCHAR, 
	"FormStatusId" VARCHAR, 
	"ForcedValidation" VARCHAR, 
	"NumberOfPread" VARCHAR NOT NULL
);
CREATE TABLE data_stay (
	"Year" VARCHAR NOT NULL, 
	"Month" VARCHAR NOT NULL, 
	"WeekNumber" VARCHAR NOT NULL, 
	"Fortnight" VARCHAR NOT NULL, 
	"#Clinic" VARCHAR NOT NULL, 
	"#MedicalDepartment" VARCHAR NOT NULL, 
	"#Doctor" VARCHAR NOT NULL, 
	"#Hospitalization Reason" VARCHAR NOT NULL, 
	"#Follow Up Reason" VARCHAR NOT NULL, 
	"NumberOfStay" VARCHAR NOT NULL
);
CREATE TABLE data_user_account (
	"Year" VARCHAR NOT NULL, 
	"Month" VARCHAR NOT NULL, 
	"WeekNumber" VARCHAR NOT NULL, 
	"Fortnight" VARCHAR NOT NULL, 
	"#Clinic" VARCHAR NOT NULL, 
	"#MedicalDepartment" VARCHAR NOT NULL, 
	"#Doctor" VARCHAR NOT NULL, 
	"#Hospitalization Reason" VARCHAR NOT NULL, 
	"#Follow Up Reason" VARCHAR NOT NULL, 
	"Created by user himself" VARCHAR NOT NULL, 
	"First Login" VARCHAR NOT NULL, 
	"NumberOfAccount" VARCHAR NOT NULL
);
CREATE TABLE doctor (
	"#Clinic" VARCHAR NOT NULL, 
	"Clinic" VARCHAR NOT NULL, 
	"#Medical Dept" VARCHAR, 
	"Medical Dept" VARCHAR, 
	"#Doctor" VARCHAR NOT NULL, 
	"Doctor Full Name" VARCHAR NOT NULL
);
CREATE TABLE doctor_list (
	"#Doctor" VARCHAR NOT NULL, 
	"Doctor Full Name" VARCHAR NOT NULL, 
	"DoctorTitle" VARCHAR, 
	"DoctorLastname" VARCHAR, 
	"DoctorFirstname" VARCHAR
);
CREATE TABLE end_reason (
	"﻿Id" VARCHAR NOT NULL, 
	"Reason" VARCHAR NOT NULL, 
	"ForceComments" VARCHAR NOT NULL, 
	"UserChoice" VARCHAR NOT NULL, 
	"LimitedToPhaseDefinitionId" VARCHAR NOT NULL, 
	"UseNotification" VARCHAR NOT NULL, 
	"ForceClosing" VARCHAR NOT NULL
);
CREATE TABLE medical_department (
	"#Clinic" VARCHAR NOT NULL, 
	"Clinic" VARCHAR NOT NULL, 
	"#Medical dept" VARCHAR NOT NULL, 
	"Medical dept" VARCHAR NOT NULL, 
	"Medical dept code" VARCHAR NOT NULL
);
CREATE TABLE medical_department_list (
	"#Medical dept" VARCHAR NOT NULL, 
	"Medical dept" VARCHAR NOT NULL, 
	"Medical dept code" VARCHAR NOT NULL
);
CREATE TABLE patient (
	"#Patient" VARCHAR NOT NULL, 
	"#PatientType" VARCHAR NOT NULL, 
	"Patient type" VARCHAR NOT NULL, 
	"#Internal Client" VARCHAR, 
	"Patient no" VARCHAR, 
	"#Gender" VARCHAR NOT NULL, 
	"Gender" VARCHAR, 
	"Birth lastname" VARCHAR NOT NULL, 
	"Birth firstname" VARCHAR NOT NULL, 
	"Lastname" VARCHAR NOT NULL, 
	"Firstname" VARCHAR NOT NULL, 
	"Birthdate" VARCHAR NOT NULL, 
	"Age gone" VARCHAR NOT NULL, 
	"Age distribution" VARCHAR NOT NULL, 
	"Medical Information" VARCHAR
);
CREATE TABLE patient_mapping (
	"#Clinique" VARCHAR NOT NULL, 
	"Clinique" VARCHAR NOT NULL, 
	"#Médecin" VARCHAR NOT NULL, 
	"Médecin" VARCHAR NOT NULL, 
	"#Patient" VARCHAR NOT NULL, 
	"#Séjour" VARCHAR NOT NULL, 
	"No séjour" VARCHAR, 
	"Séjour créé le" VARCHAR NOT NULL, 
	"Date d'intervention" VARCHAR NOT NULL, 
	"Informations médicales" VARCHAR, 
	"Séjour clos le" VARCHAR, 
	"Type de clôture" VARCHAR, 
	"Motif de clôture" VARCHAR, 
	"Commentaire de clôture" VARCHAR, 
	"Nom" VARCHAR NOT NULL, 
	"Nom de naissance" VARCHAR NOT NULL, 
	"Prénom" VARCHAR NOT NULL, 
	"Prénom de naissance" VARCHAR NOT NULL, 
	"Date de naissance" VARCHAR NOT NULL, 
	"Age révolu" VARCHAR NOT NULL, 
	"#Genre" VARCHAR NOT NULL, 
	"Genre" VARCHAR
);
CREATE TABLE patient_note (
	"UId" VARCHAR NOT NULL, 
	"PatientUId" VARCHAR NOT NULL, 
	"AuthorUId" VARCHAR NOT NULL, 
	"Comments" VARCHAR, 
	"CreatedOn" VARCHAR NOT NULL, 
	"Author" VARCHAR NOT NULL
);
CREATE TABLE patient_stay (
	"PatientStay_UId" VARCHAR NOT NULL, 
	"PatientStay_UserProfileUId" VARCHAR NOT NULL, 
	"PatientStay_PatientUId" VARCHAR NOT NULL, 
	"PatientStay_PatientStayNo" VARCHAR, 
	"PatientStay_ClinicId" VARCHAR NOT NULL, 
	"PatientStay_SurgeryDate" VARCHAR NOT NULL, 
	"PatientStay_OutingDate" VARCHAR, 
	"PatientStay_DoctorId" VARCHAR NOT NULL, 
	"PatientStay_FollowUpReasonId" VARCHAR NOT NULL, 
	"PatientStay_HospitalizationReasonId" VARCHAR NOT NULL, 
	"PatientStay_CreatedOn" VARCHAR NOT NULL, 
	"PatientStay_EndedOn" VARCHAR, 
	"PatientStay_IsActive" VARCHAR NOT NULL, 
	"PatientStay_DefaultSurveyCode" VARCHAR, 
	"PatientStay_EmergencySurveyCode" VARCHAR, 
	"PatientStay_EndReasonId" VARCHAR, 
	"PatientStay_Comments" VARCHAR, 
	"PatientStay_ProcessTypeId" VARCHAR NOT NULL, 
	"PatientStay_MatchedHospitalizationRequestUId" VARCHAR, 
	"PatientStay_HasMatchingErrors" VARCHAR NOT NULL, 
	"PatientStay_Tags" VARCHAR, 
	"PatientStay_IterationPeriod" VARCHAR NOT NULL, 
	"PatientStay_CurrentAppointmentUId" VARCHAR, 
	"PatientStay_NextAppointmentStartDate" VARCHAR, 
	"PatientStay_NextAppointmentDate" VARCHAR, 
	"PatientStay_AppointmentSpacing" VARCHAR NOT NULL, 
	"PatientStay_MedicationProtocolId" VARCHAR, 
	"PatientStay_EntryDate" VARCHAR, 
	"PatientStay_Duration" VARCHAR NOT NULL, 
	"PatientStay_HandlingMode" VARCHAR NOT NULL, 
	"PatientStay_Confirmed" VARCHAR NOT NULL, 
	"PatientStay_SSR" VARCHAR NOT NULL, 
	"PatientStay_SurgicalStay" VARCHAR NOT NULL, 
	"PatientStay_PassiveMode" VARCHAR NOT NULL, 
	"PatientStay_SurgeryConfirmationRequired" VARCHAR NOT NULL, 
	"PatientStay_PatientStatus" VARCHAR NOT NULL, 
	"PatientStay_CompanionStatus" VARCHAR NOT NULL, 
	"PatientStay_CompanionInformation" VARCHAR NOT NULL, 
	"PatientStay_CompanionCode" VARCHAR NOT NULL, 
	"PatientStay_FormStatus" VARCHAR NOT NULL, 
	"PatientStay_ForceCloseMessaging" VARCHAR NOT NULL, 
	"PatientStay_MedicalDepartmentId" VARCHAR NOT NULL, 
	"PatientStay_InteropMedicalDepartmentCode" VARCHAR, 
	"PatientStay_Year" VARCHAR NOT NULL, 
	"PatientStay_Month" VARCHAR NOT NULL, 
	"PatientStay_Week" VARCHAR NOT NULL, 
	"PatientStay_Fortnight" VARCHAR NOT NULL, 
	"PatientStay_HospitalizationNumber" VARCHAR, 
	"PatientStay_FollowUpReasonName" VARCHAR NOT NULL, 
	"PatientStay_HospitalizationReasonName" VARCHAR NOT NULL, 
	"PatientStay_MedicalDepartmentName" VARCHAR NOT NULL
);
CREATE TABLE patient_stay_evolution (
	"Date de début des symptômes" VARCHAR NOT NULL, 
	"Année de début des symptômes" VARCHAR NOT NULL, 
	"Mois de début des symptômes" VARCHAR NOT NULL, 
	"No Semaine de début des symptômes" VARCHAR NOT NULL, 
	"Quinzaine de début des symptômes" VARCHAR NOT NULL, 
	"Jour du mois de début des symptômes" VARCHAR NOT NULL, 
	"Jour de l'année de début des symptômes" VARCHAR NOT NULL, 
	"Id. Région" VARCHAR NOT NULL, 
	"Région" VARCHAR NOT NULL, 
	"Id. Etablissement" VARCHAR NOT NULL, 
	"Etablissement" VARCHAR NOT NULL, 
	"Id. Médecin" VARCHAR NOT NULL, 
	"Id. Type de patient" VARCHAR NOT NULL, 
	"Type de patient" VARCHAR NOT NULL, 
	"Id. Type de suivi" VARCHAR NOT NULL, 
	"Type de suivi" VARCHAR NOT NULL, 
	"Nombre de suivi" VARCHAR NOT NULL
);
CREATE TABLE survey_answer (
	"#Clinique" VARCHAR NOT NULL, 
	"Clinique" VARCHAR NOT NULL, 
	"#Médecin" VARCHAR NOT NULL, 
	"Médecin" VARCHAR NOT NULL, 
	"#Patient" VARCHAR NOT NULL, 
	"#Séjour" VARCHAR NOT NULL, 
	"Date création séjour" VARCHAR NOT NULL, 
	"Date d'intervention" VARCHAR NOT NULL, 
	"No séjour" VARCHAR, 
	"#Résultat" VARCHAR NOT NULL, 
	"Phase" VARCHAR NOT NULL, 
	"Date de réponse" VARCHAR NOT NULL, 
	"Répondu par le patient" VARCHAR NOT NULL, 
	"Code du questionnaire" VARCHAR NOT NULL, 
	"Titre du questionnaire" VARCHAR NOT NULL, 
	"Version du questionnaire" VARCHAR NOT NULL, 
	"Identifiant de la question" VARCHAR NOT NULL, 
	"Identifiant de la réponse" VARCHAR NOT NULL, 
	"Réponse à la question" VARCHAR NOT NULL, 
	"Questionnaire d'urgence" VARCHAR NOT NULL, 
	"Questionnaire à S+X" VARCHAR NOT NULL, 
	"Questionnaire à I+X" VARCHAR NOT NULL, 
	"Motif d'hospitalisation" VARCHAR NOT NULL, 
	"Motif de suivi" VARCHAR NOT NULL, 
	"#Alert Type" VARCHAR, 
	"Alerte déclenchée le" VARCHAR, 
	"Première prise en charge" VARCHAR, 
	"Dernière prise en charge" VARCHAR, 
	"Nombre de prise en charge" VARCHAR, 
	"Alerte clos le" VARCHAR, 
	"Commentaire de clôture" VARCHAR, 
	"Message d'alerte" VARCHAR, 
	"#Service" VARCHAR NOT NULL, 
	"Service" VARCHAR NOT NULL
);
CREATE TABLE survey_definition (
	"SurveyCode" VARCHAR NOT NULL, 
	"SurveyVersion" VARCHAR NOT NULL, 
	"Title" VARCHAR NOT NULL, 
	"PublishedOn" VARCHAR NOT NULL, 
	"NumberOfResult" VARCHAR NOT NULL
);
CREATE TABLE survey_item (
	"SurveyCode" VARCHAR NOT NULL, 
	"SurveyVersion" VARCHAR NOT NULL, 
	"ItemNo" VARCHAR NOT NULL, 
	"QuestionText" VARCHAR NOT NULL, 
	"QuestionDescription" VARCHAR, 
	"IsMandatory" VARCHAR NOT NULL, 
	"IsConditional" VARCHAR, 
	"AnswerType" VARCHAR, 
	"MinValue" VARCHAR, 
	"MaxValue" VARCHAR, 
	"Step" VARCHAR, 
	"DefaultValue" VARCHAR, 
	"Reference" VARCHAR
);
CREATE TABLE task (
	"Year" VARCHAR NOT NULL, 
	"Month" VARCHAR NOT NULL, 
	"Week" VARCHAR NOT NULL, 
	"Fortnight" VARCHAR NOT NULL, 
	"#Clinic" VARCHAR NOT NULL, 
	"#Medical Department" VARCHAR NOT NULL, 
	"#Doctor" VARCHAR NOT NULL, 
	"#Hospitalization Reason" VARCHAR NOT NULL, 
	"#Follow Up Reason" VARCHAR NOT NULL, 
	"#Task Type Id" VARCHAR NOT NULL, 
	"Task code" VARCHAR NOT NULL, 
	"Task title" VARCHAR, 
	"Task is active" VARCHAR NOT NULL, 
	"Task is for patient" VARCHAR NOT NULL, 
	"Task is mandatory" VARCHAR NOT NULL, 
	"Task is manual" VARCHAR NOT NULL, 
	"Task completed by patient" VARCHAR, 
	"Is Satisfaction Survey" VARCHAR NOT NULL, 
	"CorrelationEntity" VARCHAR, 
	"#Alert Type" VARCHAR, 
	"Number of tasks" VARCHAR NOT NULL, 
	"Number of response" VARCHAR NOT NULL, 
	"Number of alert" VARCHAR NOT NULL
);
CREATE TABLE task_detail (
	"Year" VARCHAR NOT NULL, 
	"Month" VARCHAR NOT NULL, 
	"Week" VARCHAR NOT NULL, 
	"Fortnight" VARCHAR NOT NULL, 
	"#Task" VARCHAR NOT NULL, 
	"#Clinic" VARCHAR NOT NULL, 
	"#Medical Department" VARCHAR NOT NULL, 
	"#Doctor" VARCHAR NOT NULL, 
	"#Hospitalization Reason" VARCHAR NOT NULL, 
	"#Follow Up Reason" VARCHAR NOT NULL, 
	"#Task Type Id" VARCHAR NOT NULL, 
	"Task code" VARCHAR NOT NULL, 
	"Task title" VARCHAR, 
	"Task is active" VARCHAR NOT NULL, 
	"Task is for patient" VARCHAR NOT NULL, 
	"Task is mandatory" VARCHAR NOT NULL, 
	"Task is manual" VARCHAR NOT NULL, 
	"Task completed by patient" VARCHAR, 
	"Is Satisfaction Survey" VARCHAR NOT NULL, 
	"CorrelationEntity" VARCHAR, 
	"CorrelationUId" VARCHAR, 
	"#Alert Type" VARCHAR, 
	"TaskCompletedByUId" VARCHAR, 
	"TaskCompletedUserProfileTypeId" VARCHAR
);
CREATE TABLE year (
	"Year" VARCHAR NOT NULL
);
